server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/appointment/ {
    proxy_pass http://appointment:8080/;
  }

  location /api/loyalty/ {
    proxy_pass http://loyalty:8080/;
  }
}